#wx:
#  appId: wxe479ee6d4056bfca
#  appsecret: 03a1ba839eb7b1ef4cecab4f36476ce3

wx:
  appId: wxa348ffc7dc8eabeb
  appsecret: 3b8df0b69014400bb2a1e403ae98e6c6

spring:
  datasource:
      url: jdbc:mysql://rm-bp173wox67f10yn7g.mysql.rds.aliyuncs.com:3306/sugar?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: sugar
      password: Zhq891226
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true

  jpa:
    # 配置 DBMS 类型
    database: MYSQL
    # 配置是否将执行的 SQL 输出到日志
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          # 配置开启自动更新表结构
          auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect
  mvc:
    static-path-pattern: /image/**
  resources:
    static-locations: file:/root/sugar/static/
server:
  servlet:
    context-path: /sugar/api